import { StyleSheet } from "react-native";
import { Colors } from "./Colors";

export const HomeScreenStyle = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 24,
    paddingTop: 24,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  heroCard: {
    backgroundColor: Colors.surface,
    borderRadius: 24,
    padding: 24,
    marginBottom: 24,
    boxShadow: `0px 16px 30px ${Colors.shadowSoft}`,
    elevation: 4,
  },
  heroChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: Colors.surfaceAlt,
    marginBottom: 16,
  },
  heroChipText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: "600",
    color: Colors.primary,
    textTransform: "uppercase",
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: Colors.text,
  },
  heroSubtitle: {
    fontSize: 14,
    color: Colors.subtitle,
    marginTop: 8,
  },
  heroActions: {
    flexDirection: "row",
    marginTop: 20,
  },
  heroActionPrimary: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    marginRight: 12,
  },
  heroActionPrimaryText: {
    color: Colors.buttonText,
    fontWeight: "700",
    marginLeft: 8,
  },
  heroActionSecondary: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceAlt,
  },
  heroActionSecondaryText: {
    color: Colors.primary,
    fontWeight: "700",
    marginLeft: 8,
  },
  offerCard: {
    backgroundColor: Colors.primarySoft,
    borderRadius: 24,
    padding: 24,
    marginBottom: 28,
  },
  offerBadge: {
    alignSelf: "flex-start",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: Colors.surface,
    marginBottom: 14,
  },
  offerBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.primary,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  offerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: Colors.buttonText,
  },
  offerSubtitle: {
    fontSize: 14,
    color: Colors.buttonText,
    marginTop: 8,
    opacity: 0.9,
  },
  offerFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 18,
  },
  offerMeta: {
    fontSize: 13,
    color: Colors.buttonText,
    fontWeight: "600",
  },
  offerButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: Colors.surface,
  },
  offerButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.primary,
  },
  curatedSection: {
    marginBottom: 28,
  },
  section: {
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.text,
  },
  sectionLink: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.primary,
  },
  /* filter chips removed */
  curatedModernList: {
    paddingRight: 8,
  },
  curatedCardModern: {
    backgroundColor: Colors.surface,
    borderRadius: 22,
    padding: 18,
    paddingBottom: 36, // extra space to make room for anchored footer
    marginRight: 16,
    width: 300,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.shadowSoft,
    shadowOpacity: 0.25,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    overflow: 'hidden',
  },
  curatedCardFeatured: {
    width: 300,
    backgroundColor: Colors.surface, // match regular cards for a consistent look
  },
  curatedBadgeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  curatedBadge: {
    backgroundColor: Colors.primarySoft,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  curatedBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.title,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  curatedModernTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text,
  },
  curatedModernSubtitle: {
    fontSize: 13,
    color: Colors.subtitle,
    marginTop: 8,
  },
  curatedStatsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginTop: 16,
  },
  curatedStatsRowSingle: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginTop: 12,
  },
  curatedStat: {
    width: 88,
    marginRight: 10,
    alignItems: 'flex-start',
  },
  curatedStatValue: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.text,
  },
  curatedStatLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    color: Colors.subtitle,
    letterSpacing: 0.5,
    marginTop: 2,
  },
  curatedFlavorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 14,
    marginBottom: 8,
  },
  curatedFlavorPill: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: Colors.surfaceAlt,
    marginRight: 8,
    marginBottom: 8,
  },
  curatedFlavorText: {
    fontSize: 12,
    color: Colors.text,
    fontWeight: '600',
  },
  curatedCardFooter: {
    position: 'absolute',
    left: 18,
    bottom: 12,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  curatedSommelier: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  curatedSommelierText: {
    marginLeft: 6,
    fontSize: 12,
    color: Colors.subtitle,
    fontWeight: '600',
  },
  curatedCTA: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  curatedCTAText: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.primary,
    marginRight: 4,
  },
  curatedBottle: {
    position: 'absolute',
    right: -40,
    bottom: -22,
    width: 180,
    height: 230,
    resizeMode: 'contain',
    opacity: 0.3,
  },
  curatedBottleFallback: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.surface,
    borderRadius: 90,
  },
  trendingCard: {
    backgroundColor: Colors.surface,
    borderRadius: 18,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 84,
  },
  trendingHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  trendingLogo: {
    width: 80,
    height: '100%',
    borderRadius: 12,
    marginRight: 12,
    resizeMode: 'cover',
    backgroundColor: Colors.lightGray,
  },
  trendingName: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text,
    marginLeft: 0,
  },
  trendingLocation: {
    fontSize: 13,
    color: Colors.subtitle,
  },
  trendingHighlight: {
    fontSize: 13,
    color: Colors.textPrimary,
    marginTop: 6,
  },
  trendingText: {
    flex: 1,
    paddingLeft: 12,
    justifyContent: 'center',
  },
});