import { StyleSheet } from 'react-native';
import { Colors } from './Colors';

export const ProfileScreenStyle = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    paddingTop: 24,
    paddingHorizontal: 24,
    paddingBottom: 24,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
  },
  heroCard: {
    backgroundColor: Colors.primary,
    borderRadius: 28,
    padding: 24,
    overflow: 'hidden',
    marginBottom: 28,
    boxShadow: `0px 12px 30px ${Colors.shadowSoft}`,
    elevation: 6,
  },
  heroOverlay: {
    position: 'absolute',
    right: -60,
    top: -80,
    width: 200,
    height: 200,
    borderRadius: 120,
    backgroundColor: Colors.primarySoft,
    opacity: 0.45,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 18,
  },
  initials: {
    fontSize: 32,
    fontWeight: '700',
    color: Colors.buttonText,
  },
  heroDetails: {
    flex: 1,
  },
  heroName: {
    fontSize: 26,
    fontWeight: '700',
    color: Colors.buttonText,
  },
  heroEmail: {
    marginTop: 6,
    fontSize: 14,
    color: Colors.buttonText,
    opacity: 0.85,
  },
  heroMeta: {
    marginTop: 16,
    color: Colors.buttonText,
    fontSize: 13,
    opacity: 0.9,
  },
  badge: {
    marginTop: 18,
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 14,
    backgroundColor: Colors.accent,
    borderRadius: 16,
  },
  badgeText: {
    color: Colors.buttonText,
    fontWeight: '600',
    fontSize: 12,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 18,
    paddingVertical: 18,
    paddingHorizontal: 16,
    boxShadow: `0px 8px 20px ${Colors.shadowSoft}`,
    elevation: 3,
    marginHorizontal: 6,
  },
  statLabel: {
    fontSize: 13,
    color: Colors.subtitle,
    marginBottom: 6,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '700',
    color: Colors.text,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.surface,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    flexBasis: '48%',
    boxShadow: `0px 10px 22px ${Colors.shadowSoft}`,
    elevation: 3,
    marginBottom: 12,
  },
  actionLabelGroup: {
    flexDirection: 'column',
  },
  actionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
  },
  actionSubtitle: {
    fontSize: 12,
    color: Colors.subtitle,
    marginTop: 4,
  },
  actionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 22,
    padding: 20,
    marginBottom: 28,
    boxShadow: `0px 12px 26px ${Colors.shadowSoft}`,
    elevation: 4,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.text,
  },
  sectionAction: {
    fontSize: 14,
    color: Colors.primary,
    fontWeight: '600',
  },
  favoriteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  favoriteItemLast: {
    borderBottomWidth: 0,
  },
  favoriteMeta: {
    marginLeft: 16,
  },
  favoriteName: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.text,
  },
  favoriteDetails: {
    fontSize: 13,
    color: Colors.subtitle,
    marginTop: 4,
  },
  favoriteIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.favorite,
    alignItems: 'center',
    justifyContent: 'center',
  },
  supportCard: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  supportTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: Colors.text,
    marginBottom: 8,
  },
  supportText: {
    fontSize: 13,
    color: Colors.subtitle,
    lineHeight: 20,
  },
  signOutButton: {
    marginTop: 16,
    backgroundColor: Colors.scanRed,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    boxShadow: `0px 10px 24px ${Colors.shadowSoft}`,
    elevation: 3,
  },
  signOutLabel: {
    color: Colors.buttonText,
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  chip: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: Colors.border,
    marginRight: 10,
    marginBottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipText: {
    fontSize: 12,
    color: Colors.subtitle,
  },
  // Guest user styles
  guestContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 40,
  },
  guestIcon: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: Colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  guestTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: Colors.text,
    marginBottom: 12,
    textAlign: 'center',
  },
  guestText: {
    fontSize: 15,
    color: Colors.subtitle,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 32,
  },
  guestButton: {
    width: '100%',
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 12,
  },
  guestButtonText: {
    color: Colors.buttonText,
    fontSize: 16,
    fontWeight: '600',
  },
  guestButtonSecondary: {
    width: '100%',
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 32,
  },
  guestButtonSecondaryText: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: '600',
  },
  guestDivider: {
    width: '100%',
    height: 1,
    backgroundColor: Colors.border,
    marginBottom: 24,
  },
});
