import { StyleSheet } from "react-native";
import { Colors } from "./Colors";

export const SelectedBeerScreenStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  detailsContainer: {
    width: "100%",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  imageWrapper: {
    width: "100%",
    height: 240,
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: Colors.surface,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  beerImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  imagePlaceholderText: {
    color: Colors.textSecondary,
    fontSize: 14,
  },
  imagePlaceholderFrame: {
    width: "95%",
    height: "85%",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
    padding: 8,
  },
  beerName: {
    fontSize: 24,
    fontWeight: "bold",
    color: Colors.text,
    marginBottom: 8,
    textAlign: "center",
  },
  screen: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  screenContent: {
    padding: 16,
  },
  detailsCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.shadowLight,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 12,
  },
  descriptionText: {
    fontSize: 14,
    color: Colors.text,
    marginTop: 12,
    lineHeight: 20,
  },
  sectionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 16,
    shadowColor: Colors.shadowLight,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  beerDetails: {
    fontSize: 16,
    color: Colors.text,
    marginBottom: 4,
    textAlign: "center",
  },
  metaBox: {
    width: "100%",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.border,
    marginTop: 12,
  },
  metaLeft: {
    flex: 1,
    paddingRight: 8,
  },
  metaText: {
    color: Colors.text,
    fontSize: 14,
    marginBottom: 4,
  },
  metaSubText: {
    color: Colors.subtitle,
    fontSize: 13,
  },
  metaRight: {
    minWidth: 88,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  abvLabel: {
    color: Colors.subtitle,
    fontSize: 12,
  },
  abvValue: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
  },
  ratingPriceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  ratingText: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.text,
    marginLeft: 4,
  },
  ratingCount: {
    fontSize: 14,
    color: Colors.subtitle,
    marginLeft: 2,
  },
  priceContainer: {
    alignItems: "flex-end",
  },
  priceLabel: {
    fontSize: 12,
    color: Colors.subtitle,
    marginBottom: 2,
  },
  priceValue: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.primary,
  },
  // New Modern Design Styles
  statsGrid: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: Colors.border,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  statIconRow: {
    marginBottom: 8,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: Colors.subtitle,
    textAlign: "center",
    fontWeight: "500",
  },
  infoSection: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  infoRow: {
    marginBottom: 12,
  },
  infoRowLast: {
    marginBottom: 0,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  infoTextContainer: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 11,
    color: Colors.subtitle,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  infoValue: {
    fontSize: 15,
    color: Colors.text,
    fontWeight: "500",
  },
  descriptionSection: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  descriptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  descriptionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.text,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  descriptionText: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 22,
    opacity: 0.9,
  },
  favoriteButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: Colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 1,
    height: 48,
  },
  favoriteButtonText: {
    marginLeft: 8,
    fontSize: 15,
    fontWeight: "700",
    color: Colors.primary,
  },
  favoriteButtonGuest: {
    backgroundColor: Colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Colors.primarySoft,
  },
  favoriteButtonTextGuest: {
    color: Colors.primary,
    fontWeight: "700",
    fontSize: 15,
  },
  reviewsContainer: {
    marginTop: 24,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18, 
    fontWeight: "bold", 
    color: "#000",
    marginBottom: 8, 
  },
  reviewsTitle: {
    fontSize: 18, 
    fontWeight: "bold", 
    color: "#000", 
    marginTop: 16, 
    marginBottom: 8, 
  },
  reviewItem: {
  },
  reviewSeparator: {
    height: 1,
    backgroundColor: Colors.border,
    marginBottom: 8,
  },
  reviewCard: {
    backgroundColor: Colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 12,
    shadowColor: Colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
  },
  reviewText: {
    marginTop: 4,
    color: Colors.text,
    fontSize: 14,
  },
  reviewDate: {
    marginTop: 4,
    color: "gray",
    fontSize: 12,
  },
  reviewStars: {
    marginTop: 4,
    color: Colors.subtitle,
    fontSize: 12,
  },
  reviewAuthor: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginTop: 4,
  },
  // Review Form Styles
  reviewFormContainer: {
    gap: 20,
  },
  ratingSection: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  ratingHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  ratingLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text,
    flex: 1,
  },
  starsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
  },
  ratingValue: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.starYellow,
  },
  textSection: {
    backgroundColor: Colors.surfaceAlt,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  textHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  textLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text,
  },
  reviewInput: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: Colors.text,
    fontSize: 15,
    minHeight: 100,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  submitButtonText: {
    color: Colors.buttonText,
    fontWeight: "700",
    fontSize: 16,
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: Colors.surfaceAlt,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: Colors.shadowLight,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 1,
    height: 48,
  },
  shareButtonText: {
    marginLeft: 8,
    fontSize: 15,
    fontWeight: "700",
    color: Colors.primary,
  },
  reviewContainer: {
    marginTop: 24,
    paddingHorizontal: 16, 
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 8,
  },
  checkbox: {
    marginRight: 8,
  },
  checkboxLabel: {
    fontSize: 14,
    color: "#333",
  },
  reviewGuestContainer: {
    // inner container used inside a section card — keep layout only
    backgroundColor: Colors.transparent,
    alignItems: 'center',
    padding: 0,
    borderWidth: 0,
    marginTop: 0,
  },
  reviewGuestTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.text,
    marginTop: 12,
    textAlign: "center",
  },
  reviewGuestText: {
    fontSize: 14,
    color: Colors.subtitle,
    textAlign: "center",
    marginVertical: 12,
    lineHeight: 20,
  },
  reviewGuestButton: {
    width: "100%",
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    marginBottom: 8,
  },
  reviewGuestButtonText: {
    color: Colors.buttonText,
    fontSize: 16,
    fontWeight: "600",
  },
  reviewGuestButtonSecondary: {
    width: "100%",
    backgroundColor: Colors.surface,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.primary,
  },
  reviewGuestButtonSecondaryText: {
    color: Colors.primary,
    fontSize: 16,
    fontWeight: "600",
  },
});