import { StyleSheet } from "react-native";
import { Colors } from "./Colors";

export const ScanScreenStyle = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.scannerBackground,
  },
  cameraWrapper: {
    flex: 1,
    position: "relative",
  },
  camera: {
    flex: 1,
  },
  overlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 24,
    justifyContent: "center",
    alignItems: "center",
    gap: 28,
  },
  reticle: {
    width: "74%",
    aspectRatio: 1,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: Colors.overlayLight,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.08)",
    zIndex: 2,
  },
  reticleInner: {
    width: "82%",
    aspectRatio: 1,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: Colors.primary,
    borderStyle: "dashed",
    justifyContent: "center",
    alignItems: "center",
  },
  instructionCard: {
    width: "82%",
    borderRadius: 22,
    backgroundColor: "rgba(10,10,10,0.55)",
    paddingVertical: 20,
    paddingHorizontal: 18,
    alignItems: "center",
    gap: 12,
    position: "absolute",
    alignSelf: "center",
    bottom: 120,
    zIndex: 1,
  },
  instructionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: Colors.scannerWhite,
  },
  instructionCopy: {
    fontSize: 14,
    color: Colors.scannerWhite,
    textAlign: "center",
    lineHeight: 20,
    opacity: 0.8,
  },
  scanLine: {
    position: "absolute",
    top: "50%",
    marginTop: -2,
    width: "78%",
    height: 4,
    borderRadius: 2,
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    zIndex: 0,
  },
  transparentButton: {
    paddingHorizontal: 26,
    paddingVertical: 12,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.45)",
    backgroundColor: "transparent",
  },
  transparentButtonLabel: {
    color: Colors.scannerWhite,
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  cameraButton: {
    marginTop: 6,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    alignSelf: "center",
    bottom: 30,
    zIndex: 1,
  },
  centerWrapper: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  cameraRing: {
    width: 84,
    height: 84,
    borderRadius: 42,
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.85)",
    backgroundColor: "rgba(0,0,0,0.25)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 8,
  },
  cameraCore: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.primary,
    borderWidth: 2,
    borderColor: Colors.scannerWhite,
  },
  preview: {
    ...StyleSheet.absoluteFillObject,
  },
});
